### ISSUE TITLE
No srt subtitle after introduction

### ISSUE THREAD

**Issue by danialbehzadi** [vitalyrepin/FreedomRMS#1]
Hey,

The introduction of the course has a nice srt subtitle file, but there is no srt in the weeks subtitle directory.
Can you provide them?

**Comment by vitalyrepin** [comment]
I do not have them. 

You can contribute to the project by creating subtitles.  The project is here: https://github.com/vitalyrepin/FreedomRMS/tree/master/subtitles  Check README.MD for the way to work with subtitles.
